/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//package blooddonation;
import Database.*;
import java.text.ParseException;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
//import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
/**
 *
 * @author Sara
 */
public class FirstFrame extends javax.swing.JFrame {

    /**
     * Creates new form FirstFrame
     */
    public FirstFrame() {
        initComponents();
        tempVerifier =new InputVerifier() {
                    @Override
                    public boolean verify(JComponent input) {
                        String text = ((JTextField) input).getText();
                        if ((text.matches("\\d\\d-\\d\\d-\\d\\d\\d\\d")))
                            if( (1 <= Integer.parseInt(text.split("-")[0]) && Integer.parseInt(text.split("-")[0]) <= 31) && (1 <= Integer.parseInt(text.split("-")[1]) && Integer.parseInt(text.split("-")[1]) <= 12) && (Integer.parseInt(text.split("-")[2]) <= LocalDate.now().getYear()))
                                return true;
                            else{
                                JOptionPane.showMessageDialog(rootPane, "Correct Format is: DD-MM-YYYY, Ex: 10-03-2001");                            
                                return false;
                            }
                        else if( text.matches(""))
                            return true;
                        else{
                            JOptionPane.showMessageDialog(rootPane, "Correct Format is: DD-MM-YYYY, Ex: 10-03-2001");
                            return false;
                        }
                    }
                };
        tempVerifierNumbers =new InputVerifier() {
                    @Override
                    public boolean verify(JComponent input) {
                        String text = ((JTextField) input).getText();
                        if ((text.matches("\\d\\d\\d\\d-\\d\\d\\d\\d-\\d\\d\\d\\d")) || text.matches(""))
                                return true;
                        else{
                            JOptionPane.showMessageDialog(rootPane, "Enter Number in the format XXXX-XXXX-XXXX");
                            return false;
                        }
                    }
                };
        tempVerifierQuantity =new InputVerifier() {
                    @Override
                    public boolean verify(JComponent input) {
                        String text = ((JTextField) input).getText();
                        if ((text.matches("\\d")))
                                return true;
                        else{
                            JOptionPane.showMessageDialog(null, "Enter Number between 1-9");
                            return false;
                        }
                    }
                };
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    public void Initializer(){
        	emf = Persistence.createEntityManagerFactory("com.mycompany_BloodDonationProgram_jar_1.0-SNAPSHOTPU");
        	EM = emf.createEntityManager();
        	tempDonator=new Donators();
        	tempReception = new Reception();
        	tempPatient=new Patients();
        	tempNurse = new Nurses();
        	tempLab = new Lab();
        	tempBloodbank = new Bloodbank();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        MainRegDonator = new javax.swing.JButton();
        MainRegPatient = new javax.swing.JButton();
        MainAddNurse = new javax.swing.JButton();
        MainDonateBlood = new javax.swing.JButton();
        MainRequestBlood = new javax.swing.JButton();
        jbtnRD_View = new javax.swing.JButton();
        jbtnRD_View1 = new javax.swing.JButton();
        jbtnRD_View2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.red);
        setExtendedState(6);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RECEPTION");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(580, 30, 670, 100);

        MainRegDonator.setBackground(new java.awt.Color(102, 102, 102));
        MainRegDonator.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MainRegDonator.setText("Register Donator");
        MainRegDonator.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 1, true));
        MainRegDonator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainRegDonatorActionPerformed(evt);
            }
        });
        getContentPane().add(MainRegDonator);
        MainRegDonator.setBounds(1700, 160, 160, 50);

        MainRegPatient.setBackground(new java.awt.Color(102, 102, 102));
        MainRegPatient.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MainRegPatient.setText("Register Patient");
        MainRegPatient.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 1, true));
        MainRegPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainRegPatientActionPerformed(evt);
            }
        });
        getContentPane().add(MainRegPatient);
        MainRegPatient.setBounds(1700, 360, 160, 50);

        MainAddNurse.setBackground(new java.awt.Color(102, 102, 102));
        MainAddNurse.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MainAddNurse.setText("Sign up Nurse");
        MainAddNurse.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 1, true));
        MainAddNurse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainAddNurseActionPerformed(evt);
            }
        });
        getContentPane().add(MainAddNurse);
        MainAddNurse.setBounds(1700, 260, 160, 50);

        MainDonateBlood.setBackground(new java.awt.Color(102, 102, 102));
        MainDonateBlood.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MainDonateBlood.setText("Donate Blood");
        MainDonateBlood.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 1, true));
        MainDonateBlood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainDonateBloodActionPerformed(evt);
            }
        });
        getContentPane().add(MainDonateBlood);
        MainDonateBlood.setBounds(1700, 610, 160, 50);

        MainRequestBlood.setBackground(new java.awt.Color(102, 102, 102));
        MainRequestBlood.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MainRequestBlood.setText("Request Blood");
        MainRequestBlood.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 1, true));
        MainRequestBlood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainRequestBloodActionPerformed(evt);
            }
        });
        getContentPane().add(MainRequestBlood);
        MainRequestBlood.setBounds(1700, 710, 160, 50);

        jbtnRD_View.setBackground(new java.awt.Color(102, 102, 102));
        jbtnRD_View.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jbtnRD_View.setText("View Patients");
        jbtnRD_View.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 0, 0), null, null));
        jbtnRD_View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRD_ViewActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnRD_View);
        jbtnRD_View.setBounds(1310, 870, 160, 50);

        jbtnRD_View1.setBackground(new java.awt.Color(102, 102, 102));
        jbtnRD_View1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jbtnRD_View1.setText("View Donators");
        jbtnRD_View1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 0, 0), null, null));
        jbtnRD_View1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRD_View1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnRD_View1);
        jbtnRD_View1.setBounds(1090, 870, 160, 50);

        jbtnRD_View2.setBackground(new java.awt.Color(102, 102, 102));
        jbtnRD_View2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jbtnRD_View2.setText("View Nurses");
        jbtnRD_View2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 0, 0), null, null));
        jbtnRD_View2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRD_View2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnRD_View2);
        jbtnRD_View2.setBounds(870, 870, 160, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Taymoor\\OneDrive\\Documents\\NetBeansProjects\\BloodDonationProgram\\blood-bg.jpg")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 0, 1930, 1030);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MainRegDonatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainRegDonatorActionPerformed
        this.Initializer();
        tempQuery = EM.createNamedQuery("Donators.findNewDID");
        countNewDID_DRegister = 1 + Integer.parseInt(tempQuery.getResultList().get(0).toString());
        countNewRID = 1 + Integer.parseInt(EM.createNamedQuery("Reception.findNewRID").getResultList().get(0).toString());
        RegDonatorFrame tempRegDonatorFrame= new RegDonatorFrame();
        tempRegDonatorFrame.jtxtRD_DID.setText(Integer.toString(countNewDID_DRegister));
        tempRegDonatorFrame.setVisible(true);
    }//GEN-LAST:event_MainRegDonatorActionPerformed

    private void MainRegPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainRegPatientActionPerformed
        this.Initializer();
        tempQuery = EM.createNamedQuery("Patients.findNewPID");
        countNewPID_PRegister = 1 + Integer.parseInt(tempQuery.getResultList().get(0).toString());
        countNewRID = 1 + Integer.parseInt(EM.createNamedQuery("Reception.findNewRID").getResultList().get(0).toString());
        RegPatientFrame tempRegPatientFrame= new RegPatientFrame();
        tempRegPatientFrame.jtxtRP_PID.setText(Integer.toString(countNewPID_PRegister));
        tempRegPatientFrame.setVisible(true);
    }//GEN-LAST:event_MainRegPatientActionPerformed

    private void MainAddNurseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainAddNurseActionPerformed
        this.Initializer();
        tempQuery = EM.createNamedQuery("Nurses.findNewNID");
        countNewNID_NRegister = 1 + Integer.parseInt(tempQuery.getResultList().get(0).toString());
        countNewRID = 1 + Integer.parseInt(EM.createNamedQuery("Reception.findNewRID").getResultList().get(0).toString());
         SignNurseFrame tempSignNurseFrame= new SignNurseFrame();
        tempSignNurseFrame.jtxtRN_NID.setText(Integer.toString(countNewNID_NRegister));
        tempSignNurseFrame.setVisible(true);
    }//GEN-LAST:event_MainAddNurseActionPerformed

    private void MainDonateBloodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainDonateBloodActionPerformed
        new LabDonatorsFrame().setVisible(true);
    }//GEN-LAST:event_MainDonateBloodActionPerformed

    private void MainRequestBloodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainRequestBloodActionPerformed
        new LabPatientsFrame().setVisible(true);
    }//GEN-LAST:event_MainRequestBloodActionPerformed

    private void jbtnRD_ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRD_ViewActionPerformed
        RegPatientFrame.viewPatients();
    }//GEN-LAST:event_jbtnRD_ViewActionPerformed

    private void jbtnRD_View1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRD_View1ActionPerformed
        RegDonatorFrame.viewPatients();
    }//GEN-LAST:event_jbtnRD_View1ActionPerformed

    private void jbtnRD_View2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRD_View2ActionPerformed
        SignNurseFrame.viewNurse();
    }//GEN-LAST:event_jbtnRD_View2ActionPerformed

    

    public EntityManagerFactory emf;
    public EntityManager EM;
    public Donators tempDonator;
    public Reception tempReception;
    public Patients tempPatient;
    public Nurses tempNurse;
    public Lab tempLab;
    public Bloodbank tempBloodbank;
    public Query tempQuery;
    public static int countNewDID_DRegister,countNewRID,countNewPID_PRegister,countNewNID_NRegister;
    public static InputVerifier tempVerifier;
    public static InputVerifier tempVerifierNumbers;
    public static InputVerifier tempVerifierQuantity;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MainAddNurse;
    private javax.swing.JButton MainDonateBlood;
    private javax.swing.JButton MainRegDonator;
    private javax.swing.JButton MainRegPatient;
    private javax.swing.JButton MainRequestBlood;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbtnRD_View;
    private javax.swing.JButton jbtnRD_View1;
    private javax.swing.JButton jbtnRD_View2;
    // End of variables declaration//GEN-END:variables
}
