/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import Database.*;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;
/**
 *
 * @author Sara
 */
public class GiveBloodFrame extends javax.swing.JFrame {

    /**
     * Creates new form GiveBloodFrame
     */
    public GiveBloodFrame() {
        initComponents();
        this.setDefaultCloseOperation(GiveBloodFrame.HIDE_ON_CLOSE);  
        this.jTextField1.setInputVerifier(FirstFrame.tempVerifierQuantity);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jcobGB_Units = new javax.swing.JComboBox<>();
        jcobGB_Nurses = new javax.swing.JComboBox<>();
        jbtGB_submit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Receiving Blood");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(230, 40, 340, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Available Blood Units :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(280, 150, 148, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Available Nurses :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(280, 200, 130, 20);

        jPanel1.add(jcobGB_Units);
        jcobGB_Units.setBounds(430, 150, 99, 22);

        jPanel1.add(jcobGB_Nurses);
        jcobGB_Nurses.setBounds(430, 200, 99, 22);

        jbtGB_submit.setText("Submit");
        jbtGB_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtGB_submitActionPerformed(evt);
            }
        });
        jPanel1.add(jbtGB_submit);
        jbtGB_submit.setBounds(340, 320, 122, 32);

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Required Units :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(280, 250, 130, 20);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(430, 250, 100, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Taymoor\\OneDrive\\Documents\\NetBeansProjects\\BloodDonationProgram\\blood.jpg")); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(-50, 0, 810, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtGB_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtGB_submitActionPerformed
        this.Initializer();
        String []tempFinal = this.jcobGB_Units.getSelectedItem().toString().split(" ");
        int count=0,counter=0;
        ArrayList<Integer> Selected = new ArrayList<Integer>();
        if(!this.jTextField1.getText().equals("0")){
            count = Integer.parseInt(this.jTextField1.getText());
            for(int i=0;i<Integer.parseInt(this.jTextField1.getText());i++){
                for(Bloodbank B: (List<Bloodbank>)EM.createNamedQuery("Bloodbank.findByBloodtype").setParameter("bloodtype", tempFinal[0]).getResultList()){
                    EM.getTransaction().begin();
                    B.setQuantity(B.getQuantity().subtract(BigInteger.ONE));
                    counter++;
                    count--;
                    if(Integer.parseInt(B.getQuantity().toString()) <= 0){
                        EM.remove(B);
                    }
                    EM.getTransaction().commit();
                }
            }
            if (count != 0) {
                    for (int k = 0; k < this.jcobGB_Units.getItemCount(); k++) {
                        if (this.jcobGB_Units.getSelectedIndex() != k && !Selected.contains(k)) {
                            Selected.add(k);
                            tempFinal = this.jcobGB_Units.getItemAt(k).toString().split(" ");
                            for (Bloodbank B : (List<Bloodbank>) EM.createNamedQuery("Bloodbank.findByBloodtype").setParameter("bloodtype", tempFinal[0]).getResultList()) {
                                EM.getTransaction().begin();
                                B.setQuantity(B.getQuantity().subtract(BigInteger.ONE));
                                count--;
                                counter++;
                                if (Integer.parseInt(B.getQuantity().toString()) <= 0) {
                                    EM.remove(B);
                                }
                                EM.getTransaction().commit();
                                if(count == 0){
                                    break;
                                }
                            }
                            if(count == 0){
                                break;
                            }
                        }
                    }
                    if(count != 0){
                        JOptionPane.showMessageDialog(null, "Sadly, No more available units");                    
                    }
            }
            EM.close();
            JOptionPane.showMessageDialog(null, "Removed "+ counter +" Units Successfully!");
        }
        else{
            JOptionPane.showMessageDialog(null, "Please enter Quantity between 1-9");
        }
        this.dispose();
    }//GEN-LAST:event_jbtGB_submitActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiveBloodFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiveBloodFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiveBloodFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiveBloodFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiveBloodFrame().setVisible(true);
            }
        });
    }
    public void Initializer(){
        	emf = Persistence.createEntityManagerFactory("com.mycompany_BloodDonationProgram_jar_1.0-SNAPSHOTPU");
        	EM = emf.createEntityManager();
        	tempDonator=new Donators();
        	tempReception = new Reception();
        	tempPatient=new Patients();
        	tempNurse = new Nurses();
        	tempLab = new Lab();
        	tempBloodbank = new Bloodbank();
     	}
    public EntityManagerFactory emf;
    public EntityManager EM;
    public Donators tempDonator;
    public Reception tempReception;
    public Patients tempPatient;
    public Nurses tempNurse;
    public Lab tempLab;
    public Bloodbank tempBloodbank;
    public Query tempQuery;
    public int countNewDID_DRegister,countNewRID;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbtGB_submit;
    public javax.swing.JComboBox<String> jcobGB_Nurses;
    public javax.swing.JComboBox<String> jcobGB_Units;
    // End of variables declaration//GEN-END:variables
}
