/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import Database.*;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import static java.lang.String.format;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.swing.JRViewer;
import oracle.jdbc.pool.OracleDataSource;
/**
 *
 * @author Sara
 */
public class RegDonatorFrame extends javax.swing.JFrame {

    /**
     * Creates new form RegDonatorFrame
     */
    public RegDonatorFrame() {
        initComponents();
        this.setDefaultCloseOperation(RegDonatorFrame.HIDE_ON_CLOSE); 
        this.Initializer();
        this.jtxtRD_DOB.setInputVerifier(FirstFrame.tempVerifier);
        this.jtxtRD_LastDD.setInputVerifier(FirstFrame.tempVerifier);
        this.jtxtRD_Phone.setInputVerifier(FirstFrame.tempVerifierNumbers);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jtxtRD_DID = new javax.swing.JTextField();
        jtxtRD_DOB = new javax.swing.JTextField();
        jtxtRD_Address = new javax.swing.JTextField();
        jtxtRD_Phone = new javax.swing.JTextField();
        jtxtRD_Name = new javax.swing.JTextField();
        jtxtRD_LastDD = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jbtnRD_RegisterD = new javax.swing.JButton();
        jbtnRD_Clear = new javax.swing.JButton();
        jRadioButtonMale_DR = new javax.swing.JRadioButton();
        jRadioButtonFemale_DR = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Donator ID");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 204, 255), null, null));

        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Birth Date");
        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 204, 255), null, null));

        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Address");
        jLabel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 204, 255), null, null));

        jLabel11.setForeground(new java.awt.Color(204, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Phone");
        jLabel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 204, 255), null, null));

        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Gender");
        jLabel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 204, 255), null, null));

        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Name");
        jLabel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 204, 255), null, null));

        jLabel14.setForeground(new java.awt.Color(204, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Last Donation Date");
        jLabel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 204, 255), null, null));

        jtxtRD_DID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtRD_DID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtRD_DID.setEnabled(false);
        jtxtRD_DID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtRD_DIDActionPerformed(evt);
            }
        });

        jtxtRD_DOB.setToolTipText("DD/MM/YYYY");
        jtxtRD_DOB.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jtxtRD_DOBInputMethodTextChanged(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Donators Information ");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

        jbtnRD_RegisterD.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jbtnRD_RegisterD.setForeground(new java.awt.Color(102, 102, 255));
        jbtnRD_RegisterD.setText("Register");
        jbtnRD_RegisterD.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 0, 0), null, null));
        jbtnRD_RegisterD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRD_RegisterDActionPerformed(evt);
            }
        });

        jbtnRD_Clear.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jbtnRD_Clear.setForeground(new java.awt.Color(102, 102, 255));
        jbtnRD_Clear.setText("Clear");
        jbtnRD_Clear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 0, 0), null, null));
        jbtnRD_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRD_ClearActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonMale_DR);
        jRadioButtonMale_DR.setSelected(true);
        jRadioButtonMale_DR.setText("Male");
        jRadioButtonMale_DR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMale_DRActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonFemale_DR);
        jRadioButtonFemale_DR.setText("Female");
        jRadioButtonFemale_DR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFemale_DRActionPerformed(evt);
            }
        });

        jLabel2.setText("DD-MM-YYYY");

        jLabel3.setText("DD-MM-YYYY");

        jLabel4.setText("XXXX-XXXX-XXXX");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtxtRD_DOB, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addComponent(jtxtRD_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtxtRD_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addComponent(jtxtRD_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtxtRD_LastDD, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addComponent(jtxtRD_DID, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jRadioButtonMale_DR, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonFemale_DR))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jbtnRD_RegisterD, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnRD_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtRD_DID, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtRD_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jtxtRD_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtRD_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonFemale_DR)
                    .addComponent(jRadioButtonMale_DR))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtRD_DOB, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtRD_LastDD, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnRD_RegisterD, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnRD_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jtxtRD_DOB.getAccessibleContext().setAccessibleName("DD/MM/YYYY");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtRD_DIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtRD_DIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtRD_DIDActionPerformed

    private void jRadioButtonMale_DRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMale_DRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMale_DRActionPerformed

    private void jRadioButtonFemale_DRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFemale_DRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonFemale_DRActionPerformed

    private void jbtnRD_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRD_ClearActionPerformed
        this.jtxtRD_Address.setText("");
        this.jtxtRD_DOB.setText("");
        this.jtxtRD_LastDD.setText("");
        this.jtxtRD_Name.setText("");
        this.jtxtRD_Phone.setText("");
    }//GEN-LAST:event_jbtnRD_ClearActionPerformed

    private void jbtnRD_RegisterDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRD_RegisterDActionPerformed
        this.Initializer();
        Date DOB,LDonationDate;
        Character Gender;
        Long Phone;
        String Address,Name;
        try {
            if(!this.jtxtRD_DOB.getText().equals("") && !this.jtxtRD_LastDD.getText().equals("")){
                DOB =new SimpleDateFormat("dd/MM/yyyy").parse(this.jtxtRD_DOB.getText().replaceAll("-", "/").toString());
                LDonationDate = new SimpleDateFormat("dd/MM/yyyy").parse(this.jtxtRD_LastDD.getText().replaceAll("-", "/").toString());
            }
            else{
                JOptionPane.showMessageDialog(null, "Please Enter The Required Dates!");
                return;
            }
            if(this.jRadioButtonMale_DR.isSelected())
                Gender='M';
            else
                Gender='F';
            Name = this.jtxtRD_Name.getText();
            Address = this.jtxtRD_Address.getText();
            if(!Name.equals("") && !this.jtxtRD_Phone.getText().equals("") && !Address.equals("")){
                Phone = Long.parseLong(this.jtxtRD_Phone.getText().replaceAll("-", ""));
                this.tempDonator.setAddress(Address);
                this.tempDonator.setDid("D"+this.jtxtRD_DID.getText());
                this.tempDonator.setDob(DOB);
                this.tempDonator.setDonatorname(Name);
                this.tempReception.setRid("R"+FirstFrame.countNewRID);
                this.EM.getTransaction().begin();
                this.EM.persist(this.tempReception);
                this.EM.getTransaction().commit();
                this.tempDonator.setDorid(this.tempReception);
                this.tempDonator.setGender(Gender);
                this.tempDonator.setLastdonationdate(LDonationDate);
                this.tempDonator.setPhone(Phone);
                this.EM.getTransaction().begin();
                this.EM.clear();
                this.EM.persist(this.tempDonator);
                this.EM.getTransaction().commit();
                this.EM.close();
                JOptionPane.showMessageDialog(rootPane, "Registered Successfully");
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(null, "Please Enter The Required Information Correctly!");
                return;
            }
        } catch (ParseException ex) {
            Logger.getLogger(RegDonatorFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnRD_RegisterDActionPerformed

    private void jtxtRD_DOBInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jtxtRD_DOBInputMethodTextChanged
        
    }//GEN-LAST:event_jtxtRD_DOBInputMethodTextChanged

    public static void viewPatients(){
        Connection con;
        InputStream input;
        JasperDesign jasperDesign;
        JasperReport jasperReport;
        JasperPrint jasperPrint;
        OutputStream output;
        OracleDataSource ods;
    try {
        ods=new OracleDataSource();
        ods.setURL("jdbc:oracle:thin:@192.168.1.117:1521:XE");
        ods.setUser("c##Aamer");
        ods.setPassword("Aamer154");
        con=ods.getConnection();
        input=new FileInputStream(new File("BloodBankJR_Donators.jrxml"));
        jasperDesign=JRXmlLoader.load(input);
        jasperReport=JasperCompileManager.compileReport(jasperDesign);
        jasperPrint=JasperFillManager.fillReport(jasperReport, null, con); 
        if(!jasperPrint.getPages().isEmpty()){
            JFrame frame = new JFrame("Patients Report");
            frame.getContentPane().add(new JRViewer(jasperPrint));
            frame.pack();
            frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
            frame.setVisible(true);
            output= new FileOutputStream(new File("JR_RegisteredDonators.pdf"));
            JasperExportManager.exportReportToPdfStream(jasperPrint,output);
            JOptionPane.showMessageDialog(null, "PDF File Was Generated Successfully!");
        }
        else{
            JOptionPane.showMessageDialog(null, "No available units for the following blood type!");
        }
    }   
    catch (Exception ex) {
        ex.printStackTrace();   
    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegDonatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegDonatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegDonatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegDonatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegDonatorFrame().setVisible(true);
            }
        });
    }
    public void Initializer(){
        	emf = Persistence.createEntityManagerFactory("com.mycompany_BloodDonationProgram_jar_1.0-SNAPSHOTPU");
        	EM = emf.createEntityManager();
        	tempDonator=new Donators();
        	tempReception = new Reception();
        	tempPatient=new Patients();
        	tempNurse = new Nurses();
        	tempLab = new Lab();
        	tempBloodbank = new Bloodbank();
    }
    public EntityManagerFactory emf;
    public EntityManager EM;
    public Donators tempDonator;
    public Reception tempReception;
    public Patients tempPatient;
    public Nurses tempNurse;
    public Lab tempLab;
    public Bloodbank tempBloodbank;
    public Query tempQuery;
    public int countNewDID_DRegister,countNewRID;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButtonFemale_DR;
    private javax.swing.JRadioButton jRadioButtonMale_DR;
    private javax.swing.JButton jbtnRD_Clear;
    private javax.swing.JButton jbtnRD_RegisterD;
    private javax.swing.JTextField jtxtRD_Address;
    public javax.swing.JTextField jtxtRD_DID;
    private javax.swing.JTextField jtxtRD_DOB;
    private javax.swing.JTextField jtxtRD_LastDD;
    private javax.swing.JTextField jtxtRD_Name;
    private javax.swing.JTextField jtxtRD_Phone;
    // End of variables declaration//GEN-END:variables
}
